[package]
name = "mnemo-http"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
mnemo-application = { path = "../mnemo-application" }
mnemo-domain = { path = "../mnemo-domain" }
mnemo-ports = { path = "../mnemo-ports" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
mnemo-adapters = { path = "../mnemo-adapters" }
tower.workspace = true
