[package]
name = "mnemo-store"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
mnemo-core = { path = "../mnemo-core" }
rusqlite = { version = "0.32", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
path = "src/lib.rs"
